---
- name: Disable the default site
  file: path={{nginx_conf_dir}}/sites-enabled/default state=absent
  notify:
    - reload nginx
  tags:
    - config

- name: Remove the default configuration
  file: path={{nginx_conf_dir}}/conf.d/default.conf state=absent
  notify:
    - reload nginx
  tags:
    - config
